import type { GroupGoal, Fundraiser } from '@/types/groupGoals';

export const mockGroupGoals: GroupGoal[] = [
  {
    id: 'gg_001',
    name: 'Family Land Purchase',
    description: 'Pooling together to buy a plot of land in Lekki Phase 2 for joint development.',
    targetAmount: 5000000,
    raisedAmount: 3200000,
    currency: 'NGN',
    image: '🏠',
    memberCount: 8,
    frequency: 'monthly',
    contributionAmount: 200000,
    deadline: '2026-09-30',
    createdAt: '2026-01-15',
    status: 'active',
    category: 'property',
    creatorName: 'Adaeze O.',
    members: [
      { id: 'gm1', name: 'Adaeze O.', totalContributed: 600000, lastContributionDate: '2026-03-01' },
      { id: 'gm2', name: 'Chidi N.', totalContributed: 400000, lastContributionDate: '2026-03-01' },
      { id: 'gm3', name: 'Funke A.', totalContributed: 500000, lastContributionDate: '2026-02-28' },
      { id: 'gm4', name: 'Ibrahim M.', totalContributed: 300000, lastContributionDate: '2026-03-01' },
      { id: 'gm5', name: 'Ngozi E.', totalContributed: 400000, lastContributionDate: '2026-02-15' },
      { id: 'gm6', name: 'Yusuf K.', totalContributed: 350000, lastContributionDate: '2026-03-01' },
      { id: 'gm7', name: 'Bola T.', totalContributed: 350000, lastContributionDate: '2026-02-28' },
      { id: 'gm8', name: 'David O.', totalContributed: 300000, lastContributionDate: '2026-03-01' },
    ],
  },
  {
    id: 'gg_002',
    name: 'Office Equipment',
    description: 'Group savings to purchase shared office equipment for our co-working space.',
    targetAmount: 2000000,
    raisedAmount: 850000,
    currency: 'NGN',
    image: '🖥️',
    memberCount: 5,
    frequency: 'weekly',
    contributionAmount: 50000,
    deadline: '2026-06-30',
    createdAt: '2026-02-01',
    status: 'active',
    category: 'equipment',
    creatorName: 'Chidi N.',
    members: [
      { id: 'gm9', name: 'Chidi N.', totalContributed: 250000, lastContributionDate: '2026-03-05' },
      { id: 'gm10', name: 'Emeka C.', totalContributed: 200000, lastContributionDate: '2026-03-05' },
      { id: 'gm11', name: 'Grace I.', totalContributed: 150000, lastContributionDate: '2026-03-01' },
      { id: 'gm12', name: 'Amina B.', totalContributed: 150000, lastContributionDate: '2026-02-28' },
      { id: 'gm13', name: 'Tunde A.', totalContributed: 100000, lastContributionDate: '2026-03-05' },
    ],
  },
];

export const mockFundraisers: Fundraiser[] = [
  {
    id: 'fr_001',
    title: 'Community Tech Hub Launch',
    description: 'Help us build a tech hub for youths in the community.',
    story: 'We are raising funds to build a fully equipped tech hub in Surulere to empower local youths with digital skills. The hub will provide free access to computers, internet, and training programs.',
    targetAmount: 3000000,
    raisedAmount: 1850000,
    currency: 'NGN',
    image: '💻',
    category: 'project',
    deadline: '2026-06-30',
    createdAt: '2026-01-20',
    status: 'active',
    isPublic: true,
    creatorName: 'Adaeze O.',
    donorCount: 42,
    shareCode: 'TECHHUB2026',
    recentDonors: [
      { id: 'd1', name: 'Anonymous', amount: 50000, date: '2026-03-07', isAnonymous: true },
      { id: 'd2', name: 'Funke A.', amount: 100000, date: '2026-03-06', isAnonymous: false },
      { id: 'd3', name: 'Ibrahim M.', amount: 25000, date: '2026-03-05', isAnonymous: false },
    ],
  },
  {
    id: 'fr_002',
    title: 'Wedding Reception Fund',
    description: 'Contribute towards Ngozi & Emeka\'s wedding celebration.',
    story: 'Ngozi and Emeka are getting married! Help us make their reception a memorable event. Every contribution counts.',
    targetAmount: 1500000,
    raisedAmount: 920000,
    currency: 'NGN',
    image: '💍',
    category: 'event',
    deadline: '2026-04-15',
    createdAt: '2026-02-10',
    status: 'active',
    isPublic: true,
    creatorName: 'Ngozi E.',
    donorCount: 28,
    shareCode: 'NGOZIEMEKA',
    recentDonors: [
      { id: 'd4', name: 'Adaeze O.', amount: 50000, date: '2026-03-07', isAnonymous: false },
      { id: 'd5', name: 'Yusuf K.', amount: 30000, date: '2026-03-06', isAnonymous: false },
      { id: 'd6', name: 'Anonymous', amount: 100000, date: '2026-03-04', isAnonymous: true },
    ],
  },
  {
    id: 'fr_003',
    title: 'School Renovation Project',
    description: 'Renovate classrooms and provide learning materials for Bright Future Academy.',
    story: 'Bright Future Academy in Abeokuta needs urgent renovation. The roof is leaking, desks are broken, and students lack basic learning materials. Help us give these children a better learning environment.',
    targetAmount: 5000000,
    raisedAmount: 1200000,
    currency: 'NGN',
    image: '🏫',
    category: 'education',
    deadline: '2026-08-31',
    createdAt: '2026-02-20',
    status: 'active',
    isPublic: true,
    creatorName: 'David O.',
    donorCount: 65,
    shareCode: 'BRIGHTFUTURE',
    recentDonors: [
      { id: 'd7', name: 'Grace I.', amount: 20000, date: '2026-03-08', isAnonymous: false },
      { id: 'd8', name: 'Anonymous', amount: 200000, date: '2026-03-07', isAnonymous: true },
    ],
  },
];
